# -*- coding: utf-8 -*-
"""
Created on Mon Jun 24 09:29:31 2024

@author: surma
"""

total_first_downs = 'total_first_downs'
passing_first_downs = 'passing_first_downs'
rushing_first_downs = 'rushing_first_downs'
penalty_first_downs = 'penalty_first_downs'
third_down_attempts = 'third_down_attempts'
third_down_conversions = 'third_down_conversions'
third_down_efficiency = 'third_down_efficiency'
fourth_down_attempts = 'fourth_down_attempts'
fourth_down_conversions = 'fourth_down_conversions'
fourth_down_efficiency = 'fourth_down_efficiency'
total_offense = 'total_offense'
offense_plays = 'offensive_plays'
offense_yards_per_play = 'offense_yards_per_play'
passing_yards = 'passing_yards'
pass_attempts = 'pass_attempts'
pass_completions = 'pass_completions'
passing_yards_per_attempt = 'passing_yards_per_attempt'
passing_yards_per_completion = 'passing_yards_per_completion'
passing_long_completion = 'passing_long_completion'
pass_tds = 'pass_tds'
passing_yards_gained = 'passing_yards_gained'
passing_yards_lost = 'passing_yards_lost'
passes_intercepted = 'passes_intercepted'
sacks_allowed = 'sacks_allowed'
sacks_allowed_yards = 'sacks_allowed_yards'
rushing_yards = 'rushing_yards'
rush_attempts = 'rush_attempts'
rushing_yards_per_attempt = 'rushing_yards_per_attempt'
rush_tds = 'rush_tds'
rushing_yards_gained = 'rushing_yards_gained'
rushing_yards_lost = 'rushing_yards_lost'
rushing_long_attempt = 'rushing_long_attempt'
punt_attempts = 'punt_attempts'
punting_yards = 'punting_yards'
punting_yards_per_attempt = 'punting_yards_per_attempt'
punts_inside_20 = 'punts_inside_20'
punts_50_plus = 'punts_50_plus'
punt_touchbacks = 'punt_touchbacks'
punt_fair_catches = 'punt_fair_catches'
kickoff_attempts = 'kickoff_attempts'
kickoff_yards = 'kickoff_yards'
kickoff_yards_per_attempt = 'kickoff_yards_per_attempt'
kickoff_touchbacks = 'kickoff_touchbacks'
total_return_yards = 'total_return_yards'
punt_returns = 'punt_returns'
punt_return_yards = 'punt_return_yards'
punt_return_tds = 'punt_return_tds'
punt_return_avg = 'punt_return_avg'
kickoff_returns = 'kickoff_returns'
kickoff_return_yards = 'kickoff_return_yards'
kickoff_return_tds = 'kickoff_return_tds'
kickoff_return_avg = 'kickoff_return_avg'
interception_returns = 'interception_returns'
interception_return_yards = 'interception_return_yards'
interception_return_tds = 'interception_return_tds'
fumble_recoveries = 'fumble_recoveries'
fumble_return_yards = 'fumble_return_yards'
fumble_return_tds = 'fumble_return_tds'
penalties = 'penalties'
penalty_yards = 'penalty_yards'
fumbles = 'fumbles'
fumbles_lost = 'fumbles_lost'
sacks = 'sacks'
sack_yards = 'sack_yards'
interceptions = 'interceptions'
interception_yards = 'interception_yards'
time_of_possession = 'time_of_possession'
misc_yards = 'misc_yards'
red_zone_chances = 'red_zone_chances'
red_zone_scores = 'red_zone_scores'
xp_attempts = 'xp_attempts'
xp_made = 'xp_made'
two_point_attempts = 'two_point_attempts'
two_point_made = 'two_point_made'
fg_attempts = 'fg_attempts'
fg_made = 'fg_made'


